AWSTemplateFormatVersion: "2010-09-09"
Description:
  Create Lambda Function.

Parameters:
  S3Bucket:
    Type: String
    Default: "bedroom-app-00"
  S3Key:
    Type: String
    Default: lambda.zip

Resources:
  BedroomFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      Timeout: 30
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          S3Bucket: !Ref S3Bucket
    DependsOn:
      - LambdaExecutionRole

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: !Sub "lambda_role_${S3Bucket}"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:DeleteObject
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
          - Effect: Allow
            Action:
            - s3:ListBucket
            Resource: !Sub "arn:aws:s3:::${S3Bucket}"

Outputs:
  BedroomFunction:
    Description: The ID of the VPC
    Value:
      Fn::GetAtt:
        - "BedroomFunction"
        - "Arn"
    Export:
      Name: !Sub "${AWS::StackName}-BedroomFunctionArn"